# Generated by Django 4.1.2 on 2022-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnis',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
