# Generated by Django 4.1.2 on 2022-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0002_alumnis_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnis',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
