# Generated by Django 4.1.2 on 2022-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0003_alumnis_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnis',
            name='fname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='lname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
