# Generated by Django 4.1.2 on 2022-10-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0004_alumnis_fname_alumnis_lname_alumnis_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=255)),
                ('access', models.IntegerField(default=0)),
            ],
        ),
    ]
