# Generated by Django 4.1.2 on 2022-11-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnis',
            name='branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='yoa',
            field=models.IntegerField(default=0),
        ),
    ]
