# Generated by Django 4.1.2 on 2022-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0006_alumnis_branch_alumnis_yoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('specialization', models.CharField(default='', max_length=255)),
                ('linkedID', models.CharField(default='', max_length=255)),
                ('industry', models.CharField(default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('hname', models.CharField(default='', max_length=255)),
                ('street', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('pincode', models.IntegerField(default=0)),
            ],
        ),
    ]
