# Generated by Django 4.1.2 on 2022-11-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0007_alumniprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnis',
            name='profile',
            field=models.IntegerField(default=0),
        ),
    ]
