# Generated by Django 4.1.2 on 2022-11-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0008_alumnis_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnis',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumnis',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
