# Generated by Django 4.1.2 on 2022-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0009_remove_alumnis_id_alter_alumnis_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumniprofile',
            old_name='pincode',
            new_name='buddySys',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='hname',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='street',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='consulting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='csr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='fdp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='fi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='gf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='ic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='iv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='lps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='mdp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='placements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='research',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='se',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='sip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='ssp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
