# Generated by Django 4.1.2 on 2022-11-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0010_rename_pincode_alumniprofile_buddysys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proPic', models.FileField(upload_to='')),
            ],
        ),
    ]
