# Generated by Django 4.1.2 on 2022-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0011_alumnipropic'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnipropic',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumnipropic',
            name='proPic',
            field=models.ImageField(upload_to='alumniProPic/'),
        ),
    ]
