# Generated by Django 4.1.2 on 2022-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0012_alumnipropic_email_alter_alumnipropic_propic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnipropic',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumnipropic',
            name='email',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
