# Generated by Django 2.2.3 on 2022-11-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0012_alumnipropic_email_alter_alumnipropic_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipropic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
