# Generated by Django 4.1.2 on 2022-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0013_remove_alumnipropic_id_alter_alumnipropic_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
