# Generated by Django 4.1.2 on 2022-11-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0014_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='proPic',
            field=models.ImageField(default='', upload_to='events/'),
        ),
    ]
