# Generated by Django 2.2.3 on 2022-11-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0014_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
