# Generated by Django 3.2.10 on 2022-11-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0015_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipropic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
