# Generated by Django 4.1.2 on 2022-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0016_rename_propic_events_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='penNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='proPic',
            field=models.ImageField(default='', upload_to='FacultyProPic/'),
        ),
    ]
