# Generated by Django 4.1.2 on 2022-11-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0017_faculty_pennumber_faculty_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=1500)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
                ('pic', models.ImageField(upload_to='gallery/')),
                ('email', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
