# Generated by Django 4.1.2 on 2022-11-25 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0020_alter_feedbacks_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=300)),
                ('description', models.CharField(default='', max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 25)),
        ),
    ]
