# Generated by Django 4.1.2 on 2022-11-25 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0021_post_alter_feedbacks_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 23, 58, 1, 329554)),
        ),
    ]
